version: '{build}'

image: Visual Studio 2017
configuration: Release
skip_tags: true

before_build:
- ps: nuget restore

build:
  verbosity: minimal

after_build:
- ps: Deploy\Prepare.ps1

artifacts:
- path: Deploy\bin\DiscordChatExporter.zip
  name: DiscordChatExporter.zip

deploy:
- provider: GitHub
  tag: APPVEYOR
  release: APPVEYOR
  auth_token:
    secure: sjQHWRw29AMiVMn3MtidtWnAzAf1mJ+mkJ/7h1B9TIAHhkFrqwMK7LtXV+uNJ9AO
  artifact: DiscordChatExporter.zip
  draft: true
  on:
    branch: master
    APPVEYOR_REPO_COMMIT_MESSAGE: Update version
    APPVEYOR_REPO_COMMIT_AUTHOR: Alexey Golub
