name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET (v3.1)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x

      - name: Install .NET (v5.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Build & test
        run: dotnet test --configuration Release --logger GitHubActions

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build & publish (CLI)
        run: dotnet publish DiscordChatExporter.Cli/ -o DiscordChatExporter.Cli/bin/Publish/ --configuration Release

      - name: Build & publish (GUI)
        run: dotnet publish DiscordChatExporter.Gui/ -o DiscordChatExporter.Gui/bin/Publish/ --configuration Release

      - name: Upload build artifacts (CLI)
        uses: actions/upload-artifact@v1
        with:
          name: DiscordChatExporter.CLI
          path: DiscordChatExporter.Cli/bin/Publish/

      - name: Upload build artifact (GUI)
        uses: actions/upload-artifact@v1
        with:
          name: DiscordChatExporter
          path: DiscordChatExporter.Gui/bin/Publish/